apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval:     60s
      evaluation_interval: 60s
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"
    rule_files:
      - /etc/prometheus/prometheusrules/prometheus.allrules.yml
      - /etc/prometheus/prometheusrules/kube-rules.yml
      - /etc/prometheus/prometheusrules/node-rules.yml
      - /etc/prometheus/prometheusrules/mysql-rules.yml
    scrape_configs:
      - job_name: 'mysqld_exporter'
        static_configs:
        - targets:  
          - 10.8.80.119:9104
          - 10.8.80.120:9104
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
      - job_name: 'kube-state-metrics'
        static_configs:
        - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
      - job_name: 'node-exporter'
        static_configs:
        - targets: 
          - 10.8.80.119:3310
          - 10.8.80.120:3310
          - 10.8.80.121:3310
          - 10.8.80.122:3310
          - 10.8.80.123:3310
          - 10.8.80.150:3310
          - 10.8.80.140:3310
        relabel_configs:
        - source_labels: [__address__]
          regex: 10.8.80.119:3310
          target_label: hostname
          replacement: Node119
        - source_labels: [__address__]
          regex: 10.8.80.120:3310
          target_label: hostname
          replacement: Node120
        - source_labels: [__address__]
          regex: 10.8.80.121:3310
          target_label: hostname
          replacement: Node121
        - source_labels: [__address__]
          regex: 10.8.80.122:3310
          target_label: hostname
          replacement: Node122
        - source_labels: [__address__]
          regex: 10.8.80.123:3310
          target_label: hostname
          replacement: Node123
        - source_labels: [__address__]
          regex: 10.8.80.150:3310
          target_label: hostname
          replacement: cmscs1
        - source_labels: [__address__]
          regex: 10.8.80.140:3310
          target_label: hostname
          replacement: GW01A
      - job_name: 'kubernetes-cadvisor'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      - job_name: 'elasticsearch-exporter'
        static_configs:
          - targets: ['10.8.80.119:9114']